### ISSUE TITLE
overriding anchor on click always renders home route and then desired route

### ISSUE THREAD

**Issue by nikse** [jsguy/misojs#23]
when overriding an anchor on click event and using m.route the home controller is run everytime.

for example when doing something like this to an anchor tag that has the config set to m.route:
```
onclick = function(event) { 
  if(document.URL !== event.target.href) {
    m.route(event.target.href);
  }
  return false; // prevent default/propegation
}
```

the home route/controller is run everytime

**Comment by jsguy** [comment]
I can replicate it - it might be an issue with mithril routes, rather than miso - I'll see if I'm able to recreate it using mithril...

**Comment by jsguy** [comment]
I've logged an issue with the mithril project:

https://github.com/lhorie/mithril.js/issues/480

Also, a pen to demonstrate here:

http://codepen.io/anon/pen/ZYqGaB

**Comment by jsguy** [comment]
Ok looks like m.route needs just the route part, not the full URL, ie:

`"/two"` works fine.

Details: https://github.com/lhorie/mithril.js/issues/480

Working pen:

http://codepen.io/anon/pen/Pwyjoo

So in your case, you'll need to remove the base url from the href, something like:

`m.route(event.target.href.substr(event.target.href.lastIndexOf("/")));`

So that mithril can match the route correctly...

**Comment by nikse** [comment]
oh, wow. i thought i tried that! thanks for the update

**Comment by jsguy** [comment]
I've also made a comment in the wiki:

https://github.com/jsguy/misojs/wiki/How-miso-works#links

**Comment by nikse** [comment]
awesome! I might mention that you also do not need the config: m.route and that you need to cancel the default link event one way or another
