### ISSUE TITLE
Optimisation [Question]

### ISSUE THREAD

**Issue by dlepaux** [jsguy/misojs#26]
Your project works very well ! Thanks

I'm a fan of optimisation and i have seen something bad with mithrilJS... I'm a beginer with Mithril, so I allow myself to ask a question.

The test is :
Go to `http://localhost:6476/todos`, add an entry. Cool !
Now open DevTools and reload !
In Network tab, read the HTML from the first line, it look like this :

```html
<!doctype html>
<html>

<head>
    <link href="/css/reset.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <script>
        var misoGlobal = {
            "authenticationEnabled": false
        };
    </script>
</head>

<body class="fixed-header">
    <header id="misoHeaderNode">
        <div class="cw cf">
            <div class="logo">
                <a alt="MISO" href="/"><img src="/img/miso_logo.png"></a>
            </div>
            <nav class="left">
                <ul>
                    <li><a href="http://misojs.com/docs" target="_blank">Documentation</a></li>
                </ul>
            </nav>
            <nav class="right">
                <ul>
                    <li><a href="https://github.com/jsguy/misojs" target="_blank">Github</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <section id="misoAttachmentNode">
        <div class="cw cf">
            <style>
                .done {
                    text-decoration: line-through;
                }
            </style>
            <h1>Todos - 1 of 1 remaining</h1><button>Archive</button>
            <ul>
                <li class="">todo todo todooo todo tododooooo</li>
            </ul>
            <form><input type="text" value="" placeholder="Add todo"><button type="submit">Add</button></form>
        </div>
    </section>
    <section id="loader">
        <div class="loader"></div>
    </section>
    <section id="footer">
        <div class="cw cf">Copyright &copy; 2015 jsguy</div>
    </section>
    <script src="/miso.js"></script>
    <script src="/reload.js"></script>
</body>

</html>
```

If you take a look at the bottom of network list, you will see a request made to get todos datas.. It's useless because it double request (because data was been requested in server side). 
Worst, mihtril will remove the original html for the empty template to complete it when requests has responded
One for server and One in client side.. 

I think that this problem come from mithril, and we can't do anything in this side.. 

In the Mihtril documentation : http://mithril.js.org/routing.html
`When the URL matches a route, the respective module's controller is instantiated and passed as a parameter to the view.`

So i have tried to remove dynamicly the current route, and make a hack, but i have not succeeded.

What's your view?

**Comment by jsguy** [comment]
Hi @dlepaux,

Glad you like miso! I've addressed the question here:

https://github.com/jsguy/misojs/wiki/How-miso-works#first-page-load

The short version is: you can cache the data manually by following the example on the linked page, however depending on your app structure, it might not be saving much data as the app is a SPA (Single Page App), so that any new data requests (after the first page load) are only loaded as they are required, in a single request.

My suggestion would be to cache any data you might have on landing pages, or pages that are really data-heavy, but don't worry about smaller, (data wise), pages too much, as the user is unlikely to access them directly too often.

Even though the app is SPA, any page can be bookmarked because of how the routing works, so it is actually an advantage to have this behaviour by default.

**Comment by dlepaux** [comment]
Thank you for your very conplete answer @jsguy
